;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        dap-tooltip-mouse-motion
        helm-M-x
        indent-for-tab-command
        kill-region
        kmacro-end-macro
        org-metaright
        org-self-insert-command
        org-yank
        xref-find-definitions
        ))

(setq mc/cmds-to-run-once
      '(
        helm-M-x
        helm-find-files
        ignore
        lsp-ui-doc--handle-mouse-movement
        ))
